#!/usr/bin/env bash
# print a message for domain and subdomain

subdomain() {
	if [ $# -eq 1 ]; then
		www_rec=$(dig "www.$1" | grep -A1 'ANSWER SECTION:' | awk 'FNR == 2 {print $4}')
		lb_rec=$(dig "lb-01.$1" | grep -A1 'ANSWER SECTION:' | awk 'FNR == 2 {print $4}')
		web1_rec=$(dig "web-01.$1" | grep -A1 'ANSWER SECTION:' | awk 'FNR == 2 {print $4}')
		web2_rec=$(dig "web-02.$1" | grep -A1 'ANSWER SECTION:' | awk 'FNR == 2 {print $4}')
		www_ip=$(dig "www.$1" | grep -A1 'ANSWER SECTION:' | awk 'FNR == 2 {print $5}')
		lb_ip=$(dig "lb-01.$1" | grep -A1 'ANSWER SECTION:' | awk 'FNR == 2 {print $5}')
		web1_ip=$(dig "web-01.$1" | grep -A1 'ANSWER SECTION:' | awk 'FNR == 2 {print $5}')
		web2_ip=$(dig "web-02.$1" | grep -A1 'ANSWER SECTION:' | awk 'FNR == 2 {print $5}')
		echo "The subdomain www is a $www_rec record points to $www_ip"
		echo "The subdomain lb-01 is a $lb_rec record and points to $lb_ip"
		echo "The subdomain web-01 is a $web1_rec record and points to $web1_ip"
		echo "The subdomain web-02 is a $web2_rec record and points to $web2_ip"
	elif [ $# -eq 2 ]; then
		rec=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk 'FNR == 2 {print $4}')
		ip=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk 'FNR == 2 {print $5}')
		echo "The subdomain $2 is a $rec record and points to $ip"
	fi
}
subdomain $1 $2
