#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8.\*
sudo sed -i '/errorfile 504/a listen server' /etc/haproxy/haproxy.cfg
sudo sed -i '/listen server/a         balance roundrobin' /etc/haproxy/haproxy.cfg
sudo sed -i '/balance roundrobin/a         bind :80' /etc/haproxy/haproxy.cfg
sudo sed -i '/bind :80/a         mode http' /etc/haproxy/haproxy.cfg
sudo sed -i '/mode http/a         server 25904-web-01 3.238.125.126:80 check' /etc/haproxy/haproxy.cfg
sudo sed -i '/server 25904-web-01 3.238.125.126:80 check/a         server 25904-web-02 34.204.195.185:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy start
