#!/usr/bin/env bash
#/var/run/myscript.pid
sudo touch /var/run/myscript.pid
#containing its PID
sudo bash -c echo "$$" > /var/run/myscript.pid
#Displays To infinity and beyond
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap "I hate the kill command" SIGTERM
	trap "Y U no love me?!"  SIGINT
done
#Deletes the file /var/run/myscript.pid
rm /var/run/myscript.pid
# terminates itself when receiving a SIGQUIT or SIGTERM signal
trap "exit" SIGQUIT
