#!/usr/bin/env bash
#display fizzbuzz for multiple of 15 and fizz for multiple of 3 and buzz for mul#tiple of 5 only

for ((c=1;c < 101; c++))
do
	if [ $((c % 5)) -eq 0 ] && [ $((c % 3)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((c % 5)) -eq 0 ]
	then
		echo "Buzz"
	elif [ $((c % 3)) -eq 0 ]
	then
		echo "Fizz"
		
	else
	    echo "$c"
	fi
done
