#!/usr/bin/env bash
#display Best school 10 times and "hi" after the ninth time

COUNTER=0
while [ $COUNTER -lt 11 ]
do
    if [ $COUNTER = 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((COUNTER++))
done
