#!/usr/bin/env bash
#display no 1 - 20 with superstition

n=0
while [ $n -le 20 ]
do
	if [ $n -eq 3 ]
	then
		echo "bad luck from China"
	elif [ $n -eq 8 ]
	then
		echo "bad luck from Japan"
	elif [ $n -eq 17 ]
	then
		echo "bad luck from Italy"
	else
		echo "$n"
	fi
	((n++))
done
