#!/usr/bin/env bash
#display clock

HOURS=0
while [ $HOURS -lt 13 ]
do
    echo "Hour: $HOURS"
    MINUTES=1
    while [ $MINUTES -lt 60 ]
    do
        echo $MINUTES
	((MINUTES++))
    done
    ((HOURS++))
done
