#!/usr/bin/env bash
#check information of file

var="school"
if [ -e $var ]
then
	echo "$var file exists"
	if [ -s $var ]
	then
		echo "$var file is not empty"
		if [ -f "$var" ]
		then
			echo "$var is a regular file"
		fi
	else
		echo "$var file is empty"
	fi
else
	echo "$var file does not exist"
fi
