#!/usr/bin/env bash
# runs nginx as nginx
pkill apache2
sed -i 's/www-data/nginx/g' /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
